### ISSUE TITLE
Mixing IPv6 and IPv4 in header

### ISSUE THREAD

**Issue by koshatul** [pires/go-proxyproto#6]
I noticed while doing a little testing that if you generate the SourceAddress and DestinationAddress, it's possible to get an IPv4 address and an IPv6 address.

Example:
```
net.LookupIP("localhost")
```

Can return `::1` as the net.IP, while it's up to the user to verify that they're sending IPv4/IPv6 addresses with v4/v6 protocols, I'm wondering if this `writeVersion1` and `writeVersion2` functions should return an error if the IPs return `nil` for the protocol being sent.

I'm willing to do the PR for it, but I just thought checking if the validation should be in the package or in the user code is the right way.

**Comment by pires** [comment]
Interesting question. @nabeken @mgouline as people who seem to have recent interest in extending this library (even though no issues or PRs have been made), what do you think?

**Comment by emersion** [comment]
IMHO it would be a good idea to sanity-check this in `WriteTo`. It's a simple length check.

**Comment by pires** [comment]
Want to take a stab at it @emersion? :D

**Comment by emersion** [comment]
https://github.com/pires/go-proxyproto/pull/46 should also address this issue by returning `ErrInvalidAddress` in this case.

**Comment by pires** [comment]
@emersion I think we do this validation when reading but not when writing. For instance, in https://github.com/emersion/go-proxyproto/blob/12eabef4984542e6555bbcff086b1c56d014ddd1/v1.go#L97, I can defined a `TCPv4` transport protocol and set `::1` as the source or destination address.

In https://github.com/emersion/go-proxyproto/blob/12eabef4984542e6555bbcff086b1c56d014ddd1/v2.go#L163 we seem to be somewhat protected but if an error occurs it's not clear to me it happens because, say, I'm writing an IPv6 address when transport protocol is TCP/UDP IPv4.

**Comment by emersion** [comment]
Right, the checks are in place for v2 only. I'll send a PR for v1.

>if an error occurs it's not clear to me it happens because, say, I'm writing an IPv6 address when transport protocol is TCP/UDP IPv4.

This should return `ErrInvalidAddress`: https://github.com/emersion/go-proxyproto/blob/12eabef4984542e6555bbcff086b1c56d014ddd1/v2.go#L183
